server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 9090
#  port: 8080
spring:
  datasource:
    url: ${{secrets.DATABASE_URL}}/oruem?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: oreum_1004
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      default_batch_fetch_size: 100
    open-in-view: false
  batch:
    jdbc:
      initialize-schema: always

logging:
  level:
    '[org.hibernate.type]': TRACE
